"""app

Revision ID: 1a204c601439
Revises: 
Create Date: 2024-01-07 21:49:29.433480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a204c601439'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitati',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('ore_dormite', sa.String(length=50), nullable=True),
    sa.Column('durata_activitati', sa.String(length=50), nullable=True),
    sa.Column('mic_dejun', sa.String(length=50), nullable=True),
    sa.Column('pranz', sa.String(length=50), nullable=True),
    sa.Column('cina', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('obiectiv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ore_dormite', sa.String(length=50), nullable=True),
    sa.Column('durata_activitati', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simptome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('simptom_input', sa.String(length=255), nullable=True),
    sa.Column('simptom_select', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    op.create_table('stare_de_spirit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('stare', sa.String(length=50), nullable=True),
    sa.Column('emotie', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stare_de_spirit')
    op.drop_table('simptome')
    op.drop_table('obiectiv')
    op.drop_table('activitati')
    # ### end Alembic commands ###
